### ISSUE TITLE
[EPIC]: INIT PROJECT

### ISSUE THREAD

**Issue by nesimer** [Meknassih/back-blog-wfs#57]
<a href="https://github.com/millehorde"><img src="https://avatars1.githubusercontent.com/u/23100432?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [millehorde](https://github.com/millehorde)**
_Friday Jan 11, 2019 at 00:14 GMT_
_Originally opened as https://github.com/millehorde/BlogSpec/issues/58_

----

**Comment by Meknassih** [comment]
Closed by 8fe9678cf8a903093e3cd1c595ce2dc5b665586d
